In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('Playtennis.csv')
df

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

In [6]:
output=df['Play Tennis']
input=df.drop('Play Tennis',axis='columns')

In [7]:
from sklearn.preprocessing import LabelEncoder
le_outlook=LabelEncoder()
le_temperature=LabelEncoder()
le_humidity=LabelEncoder()
le_wind=LabelEncoder()
input['Outlook_n']=le_outlook.fit_transform(input['Outlook'])
input['Temperature_n']=le_temperature.fit_transform(input['Temperature'])
input['Humidity_n']=le_humidity.fit_transform(input['Humidity'])
input['Wind_n']=le_wind.fit_transform(input['Wind'])
input=input.drop(['Outlook','Temperature','Humidity','Wind'],axis=1)

In [8]:
input

    Outlook_n  Temperature_n  Humidity_n  Wind_n
0           2              1           0       1
1           2              1           0       0
2           0              1           0       1
3           1              2           0       1
4           1              0           1       1
5           1              0           1       0
6           0              0           1       0
7           2              2           0       1
8           2              0           1       1
9           1              2           1       1
10          2              2           1       0
11          0              2           0       0
12          0              1           1       1
13          1              2           0       0

In [9]:
from sklearn import tree
model=tree.DecisionTreeClassifier()
model.fit(input,output)

DecisionTreeClassifier()

In [10]:
model.predict(input)

array(['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'Yes', 'Yes', 'Yes', 'No'], dtype=object)